CompileFlags:
  Compiler: 'C:/VSCode/data/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-g++.exe'
  Add: [xc++,
    #
    -Wall,
    #
    -std=c++20,
    #
    # '--sysroot=C:/DevelopCode/VSCode/data/.platformio',
    #
    -std=c++17,
    #
    '-isystemC:/VSCode/data/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/freertos/include/freertos']
  Remove: [-misc-definitions-in-headers, -fno-tree-switch-conversion, -mtext-section-literals, -mlongcalls, -fstrict-volatile-bitfields]
Diagnostics:
  Suppress: ["misc-definitions-in-headers", "pp_including_mainfile_in_preamble", "misc-unused-using-decls"]
