-- Improve LSPs UI {{{
-- local icons = {
--   Class = '', -- Class' ',
--   Color = '', -- Color' ',
--   Constant = '', -- Constant' ',
--   Constructor = ' ', -- Constructor' ',
--   Enum = '了', -- Enum' ',
--   EnumMember = '', -- EnumMember' ',
--   Event = '', -- Event' ',
--   Field = ' ', -- Field' ',
--   File = '', -- File' ',
--   Folder = '', -- Folder' ',
--   Function = '󰊕 ', -- Function'󰊕 ',
--   Interface = ' ', -- Interface' ',
--   Keyword = ' ', -- Keyword' ',
--   Method = 'ƒ ', -- Method'ƒ ',
--   Module = ' ', -- Module'󰏗 ',
--   Operator = ' ', -- Operator' ',
--   Property = '', -- Property' ',
--   Reference = ' ',
--   Snippet = ' ', -- Reference' ',
--   Struct = '', -- Struct' ',
--   Text = ' ', -- Text' ',
--   TypeParameter = '', -- TypeParameter'',
--   Unit = '', -- Unit' ',
--   Value = ' ', -- Value' ',
--   Variable = ' ', -- Variable' ',
-- }
--
-- local completion_tags = vim.lsp.protocol.CompletionItemKind
-- for i, kind in pairs(completion_tags) do
--   print(kind)
-- end
-- local completion_kinds = vim.lsp.protocol.CompletionItemKind
-- opts.printTable(completion_kinds)
-- for i, kind in pairs(completion_kinds) do
--   completion_kinds[i] = icons[kind] and icons[kind] .. kind or kind
--   print(i .. '..' .. kind)
-- end
-- require('vim.lsp.protocol').CompletionItemKind = completion_kinds
-- -- }}}
-- if client.name == 'clangd' and not vim.g.have_project_conf then
--   vim.g.have_project_conf = true
--   -- local client = vim.lsp.start(vim.tbl_extend('force', vim.lsp.config.basedpyright, { root_dir = root }),
--   --   { attach = false })
--   -- if client then
--   --   vim.lsp.buf_attach_client(0, client)
--   -- end
--   local uv = vim.uv or vim.loop
--   local path = vim.fn.getcwd()
--   local fname = string.format('%s/clangd.json', path)
--   if uv.fs_stat(fname) then
--     local ok, result = pcall(vim.fn.readfile, fname)
--     if ok then
--       -- vim.lsp.disable(client.name)
--       result = table.concat(result)
--       result = vim.json.decode(result)
--       local config = vim.deepcopy(vim.lsp.config.clangd)
--       config.cmd = result.cmd
--       -- config.root_dir = client.root_dir
--
--       -- vim.lsp.buf_detach_client(buf_number, client_id)
--       vim.lsp.config(client.name, config)
--       -- vim.lsp.enable(client.name)
--       -- vim.lsp.stop_client(client_id, true)
--       client_id = vim.lsp.start(config, {
--         reuse_client = function()
--           return true
--         end,
--         bufnr = buf_number,
--         attach = true,
--         silent = false,
--       })
--       -- client_id = vim.lsp.start(vim.tbl_extend('force', vim.lsp.config.basedpyright, { root_dir = root }),
--       -- vim.lsp.buf_attach_client(buf_number, client_id)
--       return
--     end
--   end
-- end
-- local handle = io.popen("where.exe clangd") -- this gets path to program on unix
-- local avr_gcc
-- if handle then
--   avr_gcc = handle:read("*a"):sub(1, -2)
--   handle:close()
-- else
--   avr_gcc = nil;
-- end
--

-- term.env = vim.F.if_nil(term.env, conf.env)
-- term.hidden = vim.F.if_nil(term.hidden, false)
--
-- if jit.os == 'Windows' then
-- local on_windows = vim.loop.os_uname().version:match 'Windows'
-- local on_windows = jit.os:match 'Windows'
-- local function join_paths(...)
--   local path_sep = on_windows and '\\' or '/'
--   local result = table.concat({ ... }, path_sep)
--   return result
-- end
--
-- local localappdata = os.getenv("LocalAppData")
-- local runtimepath = join_paths(localappdata , 'nvim')
--
-- local temp_dir = os.getenv('TEMP')
-- local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
-- local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')
-- --
--
-- local LazyUtil = require 'lazy.core.util'
-- function _G.expand(...)
--   local expanded_value = {}
--
--   for i = 1, select('#', ...) do
--     local value = select(i, ...)
--     table.insert(expanded_value, vim.inspect(value))
--   end
--   return expanded_value
-- end
--
-- function _G.put(...)
--   local expanded_value = expand(...)
--   print(table.concat(expanded_value, '\n<<<<<\n\n'))
-- end
--
-- function _G.put_text(...)
--   local expanded_value = expand(...)
--
--   local lines = vim.split(table.concat(expanded_value, '\n'), '\n')
--   local lnum = vim.api.nvim_win_get_cursor(0)[1]
--   vim.fn.append(lnum, lines)
--   return ...
-- end
--
-- -----------------------   MY  -----------------------------
-- function _G.dump(o) -- return a string respresenting of a table
--   if type(o) == 'table' then
--     local s = '{ '
--     for k, v in pairs(o) do
--       if type(k) ~= 'number' then
--         k = '"' .. k .. '"'
--       end
--       s = s .. '[' .. k .. '] = ' .. dump(v) .. ','
--     end
--     return s .. '} '
--   elseif type(o) == 'string' then
--     return o
--   else
--     return tostring(o)
--   end
-- end

-- local bloaded = (package.loaded['which-key'] ~= nil)

-- vim.api.nvim_command 'tabnew | term'
-- vim.api.nvim_input 'i'

-- vim.api.nvim_command 'tabnew | term'
-- vim.api.nvim_input('i' .. command .. utils.enter)
-----------------------   MY  -----------------------------
-- {
--   '<leader>b',
--   group = 'buffers',
--   expand = function()
--     return require('which-key.extras').expand.buf()
--   end,
-- },
-- modes:
--
-- 		   n	    Normal
-- 		   no	    Operator-pending
-- 		   nov	    Operator-pending (forced charwise |o_v|)
-- 		   noV	    Operator-pending (forced linewise |o_V|)
-- 		   noCTRL-V Operator-pending (forced blockwise |o_CTRL-V|)
-- 				CTRL-V is one character
-- 		   niI	    Normal using |i_CTRL-O| in |Insert-mode|
-- 		   niR	    Normal using |i_CTRL-O| in |Replace-mode|
-- 		   niV	    Normal using |i_CTRL-O| in |Virtual-Replace-mode|
-- 		   nt	    Normal in |terminal-emulator| (insert goes to
-- 				Terminal mode)
-- 		   ntT	    Normal using |t_CTRL-\_CTRL-O| in |Terminal-mode|
-- 		   v	    Visual by character
-- 		   vs	    Visual by character using |v_CTRL-O| in Select mode
-- 		   V	    Visual by line
-- 		   Vs	    Visual by line using |v_CTRL-O| in Select mode
-- 		   CTRL-V   Visual blockwise
-- 		   CTRL-Vs  Visual blockwise using |v_CTRL-O| in Select mode
-- 		   s	    Select by character
-- 		   S	    Select by line
-- 		   CTRL-S   Select blockwise
-- 		   i	    Insert
-- 		   ic	    Insert mode completion |compl-generic|
-- 		   ix	    Insert mode |i_CTRL-X| completion
-- 		   R	    Replace |R|
-- 		   Rc	    Replace mode completion |compl-generic|
-- 		   Rx	    Replace mode |i_CTRL-X| completion
-- 		   Rv	    Virtual Replace |gR|
-- 		   Rvc	    Virtual Replace mode completion |compl-generic|
-- 		   Rvx	    Virtual Replace mode |i_CTRL-X| completion
-- 		   c	    Command-line editing
-- 		   cr	    Command-line editing overstrike mode |c_<Insert>|
-- 		   cv	    Vim Ex mode |gQ|
-- 		   cvr	    Vim Ex mode while in overstrike mode |c_<Insert>|
-- 		   r	    Hit-enter prompt
-- 		   rm	    The -- more -- prompt
-- 		   r?	    A |:confirm| query of some sort
-- 		   !	    Shell or external command is executing
-- 		   t	    Terminal mode: keys go to the job

-- vim.api.nvim_echo({ { "Error: Unknown target mode '" .. 'target_mode' .. "'", 'ErrorMsg' } }, true, {})
-- vim.api.nvim_echo({ { 'Failed to switch. Current mode is: ' .. 'new_mode', 'WarningMsg' } }, true, {})
-- vim.api.nvim_echo({ { 'Successfully switched to target mode: ' .. 'target_mode', 'MoreMsg' } }, true, {})
-- vim.api.nvim_echo({ { 'Successfully switched to target mode: ' .. 'target_mode', 'Normal' } }, true, {})

---------------------------------------
-- local function SetMode(target_mode)
--   -- local current_mode = vim.api.nvim_get_mode().mode
--   -- print('Current mode: ' .. current_mode)
--   if target_mode == 'n' or target_mode == 'nt' or target_mode == 'normal' or target_mode == 'normal terminal' then
--     local esc_key = vim.api.nvim_replace_termcodes('<Esc>', true, false, true)
--     vim.api.nvim_feedkeys(esc_key, 'n', false)
--     vim.api.nvim_feedkeys(esc_key, 'n', false) -- Sending Esc twice is a common robust way
--     -- print 'Attempting to switch to Normal mode'
--   elseif target_mode == 'i' or target_mode == 't' or target_mode == 'insert' or target_mode == 'terminal' then
--     vim.api.nvim_feedkeys('i', 'n', false)
--     -- print 'Attempting to switch to Insert mode'
--   elseif target_mode == 'v' or target_mode == 'visual' then
--     vim.api.nvim_feedkeys('v', 'n', false)
--     -- print 'Attempting to switch to Visual mode'
--   elseif target_mode == 'V' or target_mode == 'visual_line' then
--     vim.api.nvim_feedkeys('V', 'n', false)
--     -- print 'Attempting to switch to Line Visual mode'
--   else
--     vim.api.nvim_echo({ { "Error: Unknown target mode '" .. target_mode .. "'", 'ErrorMsg' } }, true, {})
--     return
--   end
--   -- Short delay to allow mode change to process, then get new mode
--   vim.defer_fn(function()
--     -- local new_mode = vim.api.nvim_get_mode().mode
--     -- print('New mode: ' .. new_mode)
--     -- if new_mode:sub(1, 1) == target_mode:sub(1, 1) or (target_mode == 'n' and new_mode == 'n') or (target_mode == 'nt' and new_mode == 'nt') then
--     --   vim.api.nvim_echo({ { 'Successfully switched to target mode: ' .. target_mode, 'MoreMsg' } }, true, {})
--     -- elseif target_mode == 'i' and new_mode == 'i' then
--     --   vim.api.nvim_echo({ { 'Successfully switched to target mode: ' .. target_mode, 'MoreMsg' } }, true, {})
--     -- elseif target_mode == 't' and new_mode == 't' then
--     --   vim.api.nvim_echo({ { 'Successfully switched to target mode: ' .. target_mode, 'MoreMsg' } }, true, {})
--     -- else
--     --   vim.api.nvim_echo({ { 'Failed to switch. Current mode is: ' .. new_mode, 'WarningMsg' } }, true, {})
--     -- end
--   end, 100) -- 100ms delay
-- end
---------------------------------------
-- vim.cmd('2ToggleTerm direction=' .. direction)

-- vim.api.nvim_command 'tabnew | term'
-- vim.api.nvim_input 'i'
-- vim.api.nvim_input('i make clean && make || make\n')

-- vim.api.nvim_command 'tabnew | term'
-- vim.api.nvim_input('i' .. command .. utils.enter)
