-- Improve LSPs UI {{{
-- local icons = {
--   Class = '', -- Class' ',
--   Color = '', -- Color' ',
--   Constant = '', -- Constant' ',
--   Constructor = ' ', -- Constructor' ',
--   Enum = '了', -- Enum' ',
--   EnumMember = '', -- EnumMember' ',
--   Event = '', -- Event' ',
--   Field = ' ', -- Field' ',
--   File = '', -- File' ',
--   Folder = '', -- Folder' ',
--   Function = '󰊕 ', -- Function'󰊕 ',
--   Interface = ' ', -- Interface' ',
--   Keyword = ' ', -- Keyword' ',
--   Method = 'ƒ ', -- Method'ƒ ',
--   Module = ' ', -- Module'󰏗 ',
--   Operator = ' ', -- Operator' ',
--   Property = '', -- Property' ',
--   Reference = ' ',
--   Snippet = ' ', -- Reference' ',
--   Struct = '', -- Struct' ',
--   Text = ' ', -- Text' ',
--   TypeParameter = '', -- TypeParameter'',
--   Unit = '', -- Unit' ',
--   Value = ' ', -- Value' ',
--   Variable = ' ', -- Variable' ',
-- }
--
-- local completion_tags = vim.lsp.protocol.CompletionItemKind
-- for i, kind in pairs(completion_tags) do
--   print(kind)
-- end
-- local completion_kinds = vim.lsp.protocol.CompletionItemKind
-- opts.printTable(completion_kinds)
-- for i, kind in pairs(completion_kinds) do
--   completion_kinds[i] = icons[kind] and icons[kind] .. kind or kind
--   print(i .. '..' .. kind)
-- end
-- require('vim.lsp.protocol').CompletionItemKind = completion_kinds
-- -- }}}
-- if client.name == 'clangd' and not vim.g.have_project_conf then
--   vim.g.have_project_conf = true
--   -- local client = vim.lsp.start(vim.tbl_extend('force', vim.lsp.config.basedpyright, { root_dir = root }),
--   --   { attach = false })
--   -- if client then
--   --   vim.lsp.buf_attach_client(0, client)
--   -- end
--   local uv = vim.uv or vim.loop
--   local path = vim.fn.getcwd()
--   local fname = string.format('%s/clangd.json', path)
--   if uv.fs_stat(fname) then
--     local ok, result = pcall(vim.fn.readfile, fname)
--     if ok then
--       -- vim.lsp.disable(client.name)
--       result = table.concat(result)
--       result = vim.json.decode(result)
--       local config = vim.deepcopy(vim.lsp.config.clangd)
--       config.cmd = result.cmd
--       -- config.root_dir = client.root_dir
--
--       -- vim.lsp.buf_detach_client(buf_number, client_id)
--       vim.lsp.config(client.name, config)
--       -- vim.lsp.enable(client.name)
--       -- vim.lsp.stop_client(client_id, true)
--       client_id = vim.lsp.start(config, {
--         reuse_client = function()
--           return true
--         end,
--         bufnr = buf_number,
--         attach = true,
--         silent = false,
--       })
--       -- client_id = vim.lsp.start(vim.tbl_extend('force', vim.lsp.config.basedpyright, { root_dir = root }),
--       -- vim.lsp.buf_attach_client(buf_number, client_id)
--       return
--     end
--   end
-- end
-- local handle = io.popen("where.exe clangd") -- this gets path to program on unix
-- local avr_gcc
-- if handle then
--   avr_gcc = handle:read("*a"):sub(1, -2)
--   handle:close()
-- else
--   avr_gcc = nil;
-- end
--

-- term.env = vim.F.if_nil(term.env, conf.env)
-- term.hidden = vim.F.if_nil(term.hidden, false)
--
-- if jit.os == 'Windows' then
-- local on_windows = vim.loop.os_uname().version:match 'Windows'
-- local on_windows = jit.os:match 'Windows'
-- local function join_paths(...)
--   local path_sep = on_windows and '\\' or '/'
--   local result = table.concat({ ... }, path_sep)
--   return result
-- end
--
-- local localappdata = os.getenv("LocalAppData")
-- local runtimepath = join_paths(localappdata , 'nvim')
--
-- local temp_dir = os.getenv('TEMP')
-- local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
-- local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')
-- --
--
-- local LazyUtil = require 'lazy.core.util'
-- function _G.expand(...)
--   local expanded_value = {}
--
--   for i = 1, select('#', ...) do
--     local value = select(i, ...)
--     table.insert(expanded_value, vim.inspect(value))
--   end
--   return expanded_value
-- end
--
-- function _G.put(...)
--   local expanded_value = expand(...)
--   print(table.concat(expanded_value, '\n<<<<<\n\n'))
-- end
--
-- function _G.put_text(...)
--   local expanded_value = expand(...)
--
--   local lines = vim.split(table.concat(expanded_value, '\n'), '\n')
--   local lnum = vim.api.nvim_win_get_cursor(0)[1]
--   vim.fn.append(lnum, lines)
--   return ...
-- end
--
-- -----------------------   MY  -----------------------------
-- function _G.dump(o) -- return a string respresenting of a table
--   if type(o) == 'table' then
--     local s = '{ '
--     for k, v in pairs(o) do
--       if type(k) ~= 'number' then
--         k = '"' .. k .. '"'
--       end
--       s = s .. '[' .. k .. '] = ' .. dump(v) .. ','
--     end
--     return s .. '} '
--   elseif type(o) == 'string' then
--     return o
--   else
--     return tostring(o)
--   end
-- end

-- local bloaded = (package.loaded['which-key'] ~= nil)

-- vim.api.nvim_command 'tabnew | term'
-- vim.api.nvim_input 'i'

-- vim.api.nvim_command 'tabnew | term'
-- vim.api.nvim_input('i' .. command .. utils.enter)
-----------------------   MY  -----------------------------
-- {
--   '<leader>b',
--   group = 'buffers',
--   expand = function()
--     return require('which-key.extras').expand.buf()
--   end,
-- },
